In [1]:
import numpy as np
import pandas as pd

In [2]:
labels_path = "../../data/raw/train/labels/TRECIS_2018_2019-labels.json"
labels_raw = pd.read_json(labels_path)

labels = labels_raw.copy()
labels.head(20)

,eventID,eventName,eventDescription,eventType,postID,postCategories,postPriority
0,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72676276212731904,"[Factoid, Hashtags, News]",Low
1,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72678400833228800,"[ServiceAvailable, Official, Hashtags, News]",Critical
2,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72682396750848000,"[Sentiment, Irrelevant]",Low
3,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72693931619528704,"[ThirdPartyObservation, Hashtags, News]",Medium
4,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72698562223407104,"[ThirdPartyObservation, Hashtags, Irrelevant]",Low
5,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72760614661009408,"[Discussion, Irrelevant]",Low
6,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72787965184716800,"[ThirdPartyObservation, ServiceAvailable, Hash...",High
7,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72827930719432704,[Irrelevant],Low
8,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72864403120324608,"[SearchAndRescue, ThirdPartyObservation, Hasht...",Critical
9,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72871116724633600,"[ThirdPartyObservation, ServiceAvailable, News]",Critical
10,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73023697123938304,"[Donations, ThirdPartyObservation, Hashtags, N...",High
11,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73050416832708608,"[FirstPartyObservation, ServiceAvailable, Hash...",High
12,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73121834727518208,"[ThirdPartyObservation, Hashtags, News]",Medium
13,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73127029050060800,"[MovePeople, FirstPartyObservation, EmergingTh...",Critical
14,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73151882612326400,"[FirstPartyObservation, Official, News, NewSub...",Critical
15,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73185763981918208,[Sentiment],Low
16,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73199761230020608,"[Hashtags, Irrelevant]",Low
17,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73203170666491904,"[Sentiment, Irrelevant]",Low
18,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73203823405051904,"[FirstPartyObservation, Weather, Official, News]",Medium
19,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,73212444264243200,"[ThirdPartyObservation, EmergingThreats, News]",High

In [3]:
labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38478 entries, 0 to 38477
Data columns (total 7 columns):
eventID             38478 non-null object
eventName           38478 non-null object
eventDescription    38478 non-null object
eventType           38478 non-null object
postID              38478 non-null int64
postCategories      38478 non-null object
postPriority        38478 non-null object
dtypes: int64(1), object(6)
memory usage: 2.1+ MB

### eventID

In [4]:
print(labels.eventID.value_counts())

parisAttacks2015                  2066
nepalEarthquake2015               2048
typhoonHagupit2014                1470
nepalEarthquake2015S3             1412
nepalEarthquake2015S2             1408
                                  ...
guatemalaEarthquake2012            154
earthquakeCalifornia2014           127
italyEarthquakes2012               103
joplinTornado2011                   96
sandiegoSynagogueShooting2019B      82
Name: eventID, Length: 65, dtype: int64

In [5]:
print(labels.eventID.unique())

['joplinTornado2011' 'italyEarthquakes2012' 'fireColorado2012'
 'philipinnesFloods2012' 'costaRicaEarthquake2012'
 'guatemalaEarthquake2012' 'typhoonPablo2012' 'queenslandFloods2013'
 'bostonBombings2013' 'westTexasExplosion2013' 'albertaFloods2013'
 'manilaFloods2013' 'floodColorado2013' 'australiaBushfire2013'
 'earthquakeBohol2013' 'laAirportShooting2013' 'typhoonYolanda2013'
 'chileEarthquake2014' 'earthquakeCalifornia2014' 'typhoonHagupit2014'
 'typhoonHagupit2014S1' 'typhoonHagupit2014S2' 'nepalEarthquake2015'
 'nepalEarthquake2015S1' 'nepalEarthquake2015S4' 'nepalEarthquake2015S2'
 'nepalEarthquake2015S3' 'parisAttacks2015' 'fireYMM2016A' 'fireYMM2016B'
 'fireYMM2016C' 'fireYMM2016D' 'fireYMM2016E' 'shootingDallas2017A'
 'shootingDallas2017B' 'shootingDallas2017C' 'shootingDallas2017D'
 'shootingDallas2017E' 'flSchoolShooting2018' 'hurricaneFlorence2018A'
 'hurricaneFlorence2018B' 'hurricaneFlorence2018C'
 'hurricaneFlorence2018D' 'floodChoco2019' 'philippinesEarthquake2019B'
 'philippinesEarthquake2019C' 'philippinesEarthquake2019A'
 'philippinesEarthquake2019D' 'cycloneKenneth2019C' 'cycloneKenneth2019A'
 'cycloneKenneth2019D' 'cycloneKenneth2019B' 'southAfricaFloods2019C'
 'southAfricaFloods2019B' 'southAfricaFloods2019A'
 'sandiegoSynagogueShooting2019B' 'sandiegoSynagogueShooting2019C'
 'sandiegoSynagogueShooting2019A' 'coloradoStemShooting2019A'
 'coloradoStemShooting2019B' 'coloradoStemShooting2019C'
 'albertaWildfires2019C' 'albertaWildfires2019A' 'albertaWildfires2019D'
 'albertaWildfires2019B']

Data sets are segmented (albertaWildfires2019A, albertaWildfires2019B), for convenience purposes should be tidied up (their segment IDs removed)

In [6]:
import re

pattern = r'\w+\d{4}'
match = re.match(pattern, labels.eventID[0])
match.group()

'joplinTornado2011'

In [7]:
_eventID = labels.eventID.apply(lambda x: re.match(r'\w+\d{4}', x).group())
print(_eventID.unique())
print(len(_eventID.unique()))

['joplinTornado2011' 'italyEarthquakes2012' 'fireColorado2012'
 'philipinnesFloods2012' 'costaRicaEarthquake2012'
 'guatemalaEarthquake2012' 'typhoonPablo2012' 'queenslandFloods2013'
 'bostonBombings2013' 'westTexasExplosion2013' 'albertaFloods2013'
 'manilaFloods2013' 'floodColorado2013' 'australiaBushfire2013'
 'earthquakeBohol2013' 'laAirportShooting2013' 'typhoonYolanda2013'
 'chileEarthquake2014' 'earthquakeCalifornia2014' 'typhoonHagupit2014'
 'nepalEarthquake2015' 'parisAttacks2015' 'fireYMM2016'
 'shootingDallas2017' 'flSchoolShooting2018' 'hurricaneFlorence2018'
 'floodChoco2019' 'philippinesEarthquake2019' 'cycloneKenneth2019'
 'southAfricaFloods2019' 'sandiegoSynagogueShooting2019'
 'coloradoStemShooting2019' 'albertaWildfires2019']
33

In [8]:
labels['eventSegmentID'] = labels.eventID
labels.eventID = _eventID

labels.head()

,eventID,eventName,eventDescription,eventType,postID,postCategories,postPriority,eventSegmentID
0,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72676276212731904,"[Factoid, Hashtags, News]",Low,joplinTornado2011
1,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72678400833228800,"[ServiceAvailable, Official, Hashtags, News]",Critical,joplinTornado2011
2,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72682396750848000,"[Sentiment, Irrelevant]",Low,joplinTornado2011
3,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72693931619528704,"[ThirdPartyObservation, Hashtags, News]",Medium,joplinTornado2011
4,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,Unknown,72698562223407104,"[ThirdPartyObservation, Hashtags, Irrelevant]",Low,joplinTornado2011

### eventType

In [9]:
labels.eventType.value_counts()

Unknown    38478
Name: eventType, dtype: int64

Event types need to be gathered from the topics .xml file

In [10]:
topics_path = "../../data/raw/TRECIS-2018-2019.topics.xml"

# Manually adding root node to the xml file
# !sed -i '1s/^/<root>\n/' {topics_path}
# !sed -i '$s/$/\n<\/root>/' {topics_path}

In [11]:
import xml.etree.cElementTree as ET

attribs = ['dataset', 'type']

xtree = ET.parse(topics_path)
xroot = xtree.getroot()
rows = []

for node in xroot: 
    res = []
    for el in attribs: 
        if node is not None and node.find(el) is not None:
            res.append(node.find(el).text)
            # Sanity check
            # if el == 'num':
            #     print(node.find('num').text)
        else: 
            res.append(None)
    rows.append(
        {attribs[i]: res[i] for i, _ in enumerate(attribs)}
    )

event_types = pd.DataFrame(rows, columns=attribs)

event_types

                          dataset        type
0                fireColorado2012    wildfire
1         costaRicaEarthquake2012  earthquake
2               floodColorado2013       flood
3                typhoonPablo2012     typhoon
4           laAirportShooting2013    shooting
5          westTexasExplosion2013     bombing
6         guatemalaEarthquake2012  earthquake
7            italyEarthquakes2012  earthquake
8           philipinnesFloods2012       flood
9               albertaFloods2013       flood
10          australiaBushfire2013    wildfire
11             bostonBombings2013     bombing
12               manilaFloods2013       flood
13           queenslandFloods2013       flood
14             typhoonYolanda2013     typhoon
15              joplinTornado2011     typhoon
16            chileEarthquake2014  earthquake
17             typhoonHagupit2014     typhoon
18            nepalEarthquake2015  earthquake
19           flSchoolShooting2018    shooting
20               parisAttacks2015     bombing
21                 floodChoco2019       flood
22                fireAndover2019    wildfire
23       earthquakeCalifornia2014  earthquake
24            earthquakeBohol2013  earthquake
25          hurricaneFlorence2018     typhoon
26             shootingDallas2017    shooting
27                    fireYMM2016    wildfire
28           albertaWildfires2019    wildfire
29             cycloneKenneth2019     typhoon
30      philippinesEarthquake2019  earthquake
31       coloradoStemShooting2019    shooting
32          southAfricaFloods2019       flood
33  sandiegoSynagogueShooting2019    shooting

In [12]:
labels = pd.merge(labels, event_types, left_on='eventID', right_on='dataset')

labels.eventType = labels.type
labels.drop(columns=['type', 'dataset'], inplace=True)

labels.head()

,eventID,eventName,eventDescription,eventType,postID,postCategories,postPriority,eventSegmentID
0,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,typhoon,72676276212731904,"[Factoid, Hashtags, News]",Low,joplinTornado2011
1,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,typhoon,72678400833228800,"[ServiceAvailable, Official, Hashtags, News]",Critical,joplinTornado2011
2,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,typhoon,72682396750848000,"[Sentiment, Irrelevant]",Low,joplinTornado2011
3,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,typhoon,72693931619528704,"[ThirdPartyObservation, Hashtags, News]",Medium,joplinTornado2011
4,joplinTornado2011,2011 Joplin Tornado,The 2011 Joplin tornado was a catastrophic EF5...,typhoon,72698562223407104,"[ThirdPartyObservation, Hashtags, Irrelevant]",Low,joplinTornado2011

### postCategories

In [13]:
_postCategories = labels.postCategories.apply(pd.Series).stack()
_postCategories = pd.get_dummies(_postCategories).sum(level=0)

labels.drop(columns=['postCategories'], inplace=True)
labels = labels.join(_postCategories)

labels[['postID', *_postCategories.columns]].head()

,postID,Advice,CleanUp,ContextualInformation,Discussion,Donations,EmergingThreats,Factoid,FirstPartyObservation,GoodsServices,...,NewSubEvent,News,Official,OriginalEvent,SearchAndRescue,Sentiment,ServiceAvailable,ThirdPartyObservation,Volunteer,Weather
0,72676276212731904,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,72678400833228800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,72682396750848000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,72693931619528704,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,72698562223407104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### postPriority

In [14]:
labels.postPriority.value_counts()

Low         27477
Medium       6195
High         4382
Critical      423
Unknown         1
Name: postPriority, dtype: int64

In [15]:
labels[labels.postPriority == 'Unknown']

,eventID,eventName,eventDescription,eventType,postID,postPriority,eventSegmentID,Advice,CleanUp,ContextualInformation,...,NewSubEvent,News,Official,OriginalEvent,SearchAndRescue,Sentiment,ServiceAvailable,ThirdPartyObservation,Volunteer,Weather
254,fireColorado2012,DEMO: CrisisLex26 2012 Colorado wildfires,The 2012 Colorado wildfires were an unusually ...,wildfire,212311994286620672,Unknown,fireColorado2012,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
unknown_priority = labels[labels.postPriority == 'Unknown'].index
labels.drop(unknown_priority, axis='index', inplace=True)

labels.postPriority.value_counts()

Low         27477
Medium       6195
High         4382
Critical      423
Name: postPriority, dtype: int64

In [17]:
priority_dict = {
    'Critical': 1.0,
    'High': 0.75,
    'Medium': 0.5,
    'Low': 0.25
}

priority_num = labels.postPriority.apply(lambda x: priority_dict[x])
labels.postPriority = priority_num

labels.postPriority.head(10)

0    0.25
1    1.00
2    0.25
3    0.50
4    0.25
5    0.25
6    0.75
7    0.25
8    1.00
9    1.00
Name: postPriority, dtype: float64

### postID

In [18]:
duplicated = labels[labels.postID.duplicated()]
print(len(duplicated))

2213

In [19]:
duplicated.postID.head(10)

7993    541447468618375168
7995    541447512947556352
7997    541447536284688384
7999    541447578840080384
8001    541448043355070464
8003    541448163526057984
8005    541448307189350400
8007    541448380891680768
8009    541448458671230976
8011    541448474911592448
Name: postID, dtype: int64

In [20]:
labels[labels.postID == duplicated.postID.iloc[0]]

,eventID,eventName,eventDescription,eventType,postID,postPriority,eventSegmentID,Advice,CleanUp,ContextualInformation,...,NewSubEvent,News,Official,OriginalEvent,SearchAndRescue,Sentiment,ServiceAvailable,ThirdPartyObservation,Volunteer,Weather
7992,typhoonHagupit2014,2014 Typhoon Hagupit,"Typhoon Hagupit, known in the Philippines as T...",typhoon,541447468618375168,0.25,typhoonHagupit2014,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7993,typhoonHagupit2014,[Split Topic - Part 1] 2014 Typhoon Hagupit,"Typhoon Hagupit, known in the Philippines as T...",typhoon,541447468618375168,0.50,typhoonHagupit2014S1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

There are duplicated labellings in the data set, but no timestamp to indicate which labellings were final.

In [21]:
labels.drop_duplicates('postID', keep='last', inplace=True)

labels[labels.postID.duplicated()]

Empty DataFrame
Columns: [eventID, eventName, eventDescription, eventType, postID, postPriority, eventSegmentID, Advice, CleanUp, ContextualInformation, Discussion, Donations, EmergingThreats, Factoid, FirstPartyObservation, GoodsServices, Hashtags, InformationWanted, Irrelevant, Location, MovePeople, MultimediaShare, NewSubEvent, News, Official, OriginalEvent, SearchAndRescue, Sentiment, ServiceAvailable, ThirdPartyObservation, Volunteer, Weather]
Index: []

[0 rows x 32 columns]